name: deep_learn
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi
  - async_generator
  - attrs
  - backports
  - backports.functools_lru_cache
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - colorama
  - cycler
  - decorator
  - defusedxml
  - entrypoints
  - freeglut
  - freetype
  - icc_rt
  - icu
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jasper
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - kiwisolver
  - lcms2
  - libblas
  - libcblas
  - libclang
  - liblapack
  - liblapacke
  - libopencv
  - libpng
  - libsodium
  - libtiff
  - libwebp-base
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - msys2-conda-epoch
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - numpy
  - olefile
  - opencv
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - patsy
  - pickleshare
  - pillow
  - pip
  - plotly
  - prometheus_client
  - prompt_toolkit
  - py-opencv
  - pycparser
  - pygments
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pyrsistent
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pywin32
  - pywinpty
  - pyzmq
  - qt
  - retrying
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - simplegeneric
  - six
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - vc
  - vs2015_runtime
  - wcwidth
  - webencodings
  - wheel
  - wincertstore
  - winpty
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - alembic
    - cliff
    - cmaes
    - cmd2
    - colorlog
    - greenlet
    - mako
    - optuna
    - pbr
    - prettytable
    - pyperclip
    - pyreadline
    - python-editor
    - pyyaml
    - sqlalchemy
    - stevedore

